anytimeiv/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^', include('vw_site.urls')),
    url(r'^jobs/', include('vw_jobs.urls', namespace='jobs')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^candidates/', include('vw_candidate.urls')),
    url(r'^questions/', include('vw_question.urls')),
    url(r'^members/', include('vw_user.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

try:
    if settings.DEBUG:
        import debug_toolbar
        urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]
except:
    pass

vw_jobs/urls.py
from django.conf.urls import url

from .views import JobListView, JobUpdateView, JobDeleteView, JobCreateView, JobQuestionCreateView

urlpatterns = [
    url(r'^create/question/$', JobQuestionCreateView.as_view(), name="create_job_question"),
    url(r'^create/$', JobCreateView.as_view(), name="create_job"),
    url(r'^delete/(?P<pk>\d+)/$', JobDeleteView.as_view(), name="delete_job"),
    url(r'^update/(?P<pk>\d+)/$', JobUpdateView.as_view(), name="update_job"),
    url(r'^$', JobListView.as_view(), name="list_job"),
]

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}RightPeople{% endblock %}</title>
    {% block meta %}
        {% include "fragments/head_meta.html" %}
    {% endblock %}
    {% block extras %}
        {% include "fragments/head_extras.html" %}
    {% endblock %}

    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}

    {% block extra_meta %}{% endblock %}
    {% block extra_head %}{% endblock %}
</head>
<body class="">
    <div class="bg-dark dk" id="wrap">
        <div id="top">
            {% block top %}
            <nav class="navbar navbar-inverse navbar-static-top">
                <div class="container-fluid">
                    <div class="flex-header">
                        <header class="navbar-header">
                            <a href="{% url 'index' %}" class="navbar-brand">
                                <img src="{% static 'img/logo.png' %}" alt="RightPeople">
                            </a>
                        </header>
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="topnav">
                            <div class="btn-group">
                                <a href="{% url 'account_logout' %}" data-toggle="tooltip" data-original-title="Logout" data-placement="bottom" class="btn btn-metis-1 btn-sm">
                                    <i class="fa fa-power-off"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        <ul class="nav navbar-nav">
                            <li> <a href="{% url 'dashboard' %}">{% trans 'Dashboard' %}</a>  </li>
                            <li> <a href="{% url 'jobs:list_job' %}">{% trans 'Job listing' %}</a>  </li>
                            <li class='dropdown '>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'Templates' %} <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li> <a href="{% url 'questions' %}">{% trans 'Questions' %}</a></li>
                                    <li> <a href="{% url 'invite_messages' %}">{% trans 'Invite Message' %}</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            {% endblock %}
        </div>
        <div id="left">
            {% block left %}
            {% endblock %}
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <footer class="Footer bg-dark dker">
        <p>{% now "Y" %} &copy; {% trans 'RightPeople Anytime Interview' %}</p>
    </footer>
    {% block modal %}
    {% endblock %}
    {% block footer %}
        {% include "fragments/footer.html" %}
    {% endblock %}
    {% include 'js_urls.html' %}
    {% block extra_footer %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block top %}

{% endblock %}

{% block content %}
{% endblock %}

templates/js_urls.html
<script>

  var urlGetCandidateInfo = '{% url "get_candidate_info" %}';
  var urlPositionsSuggestions = '{% url "positions_list" %}';
  var urlPositionQuestions = '{% url "questions_position" %}';
  var urlSaveTemlate = '{% url "save_template" %}';
  var urlIsCandidateExist = "{% url 'is_candidate_exist' %}";
</script>