vw_jobs/urls.py
from django.conf.urls import url

from .views import JobListView, JobUpdateView, JobDeleteView, JobCreateView, JobQuestionCreateView

urlpatterns = [
    url(r'^create/question/$', JobQuestionCreateView.as_view(), name="create_job_question"),
    url(r'^create/$', JobCreateView.as_view(), name="create_job"),
    url(r'^delete/(?P<pk>\d+)/$', JobDeleteView.as_view(), name="delete_job"),
    url(r'^update/(?P<pk>\d+)/$', JobUpdateView.as_view(), name="update_job"),
    url(r'^$', JobListView.as_view(), name="list_job"),
]

vw_question/urls.py
from django.conf.urls import url
from vw_question.views import *


urlpatterns = [
    url(r'^$', SampleQuestionListView.as_view(), name="questions"),
    url(r'^create/$', SampleQuestionCreateView.as_view(), name="create_question"),
    url(r'^positions_list/$', PositionsList.as_view(), name="positions_list"),
    url(r'^questions_position/$', QuestionForPosition.as_view(), name="questions_position"),
    url(r'^competencies_list/$', CompetenciesList.as_view(), name="competencies_list"),
    url(r'^questions_competency/$', QuestionForCompetency.as_view(), name="questions_competency"),
    url(r'^edit/(?P<pk>\d+)$', SampleQuestionUpdateView.as_view(), name="edit_question"),
    url(r'^delete/(?P<pk>\d+)$', SampleQuestionDeleteView.as_view(), name="del_question"),
]

vw_question/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _


class SampleQuestion(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    content = models.CharField(max_length=3000)
    type = models.CharField(max_length=50)
    position = models.ForeignKey('Position', on_delete=models.SET_NULL, null=True, blank=True)
    competency = models.ForeignKey('Competency', on_delete=models.SET_NULL, null=True, blank=True)
    limit = models.IntegerField(default=2)

    def __str__(self):
        return self.content


class Position(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=255)

    def __str__(self):
        return "{0}".format(self.name)


class Competency(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return "{0}".format(self.name)

    class Meta:
        verbose_name = _('Competency')
        verbose_name_plural = _('Competencies')

vw_question/forms.py
from django import forms

from .models import SampleQuestion


class SampleQuestionForm(forms.ModelForm):
    type = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5})
    )

    class Meta:
        model = SampleQuestion
        fields = ('type', 'content', 'limit',)

    def __init__(self, *args, **kwargs):
        super(SampleQuestionForm, self).__init__(*args, **kwargs)
        self.fields['limit'].widget = forms.NumberInput(attrs={
            'class': 'form-control',
        })

vw_question/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.http import JsonResponse, StreamingHttpResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import SampleQuestionForm
from .models import SampleQuestion, Position, Competency


class AjaxRequestMixin(object):
    success_url = '/'

    def form_invalid(self, form):
        data = {
            'status': 'error',
            'form': render_to_string(self.template_name, {'form': form}, request=self.request)}
        return JsonResponse(data)

    def form_valid(self, form):
        data = {'status': 'ok'}
        return JsonResponse(data)


class SampleQuestionCreateView(AjaxRequestMixin, LoginRequiredMixin, CreateView):
    model = SampleQuestion
    form_class = SampleQuestionForm
    template_name = 'vw_question/create_form.html'
    success_url = '/'

    def form_valid(self, form):
        form_data = form.save(commit=False)
        form_data.user = self.request.user
        if self.request.POST.get('position'):
            role, _ = Position.objects.get_or_create(
                name=self.request.POST['position'],
                user=self.request.user
            )
            form_data.position = role
        if self.request.POST.get('competency'):
            role, _ = Competency.objects.get_or_create(
                name=self.request.POST['competency']
            )
            form_data.competency = role
        form_data.save()
        return super(SampleQuestionCreateView, self).form_valid(form)


class PositionsList(LoginRequiredMixin, View):
    http_method_names = ['get']
    queryset = Position.objects.all()

    def get_queryset(self, request):
        self.queryset = self.queryset.filter(user_id=self.request.user.id)
        if request.GET.get('position'):
            return self.queryset.filter(name__icontains=request.GET.get('position'))
        else:
            return self.queryset

    def get(self, request, *args, **kwargs):
        return StreamingHttpResponse(
            serializers.serialize('json', list(self.get_queryset(request)), fields=('name', 'id')),
            content_type='application/json'
        )


class QuestionForPosition(LoginRequiredMixin, View):
    http_method_names = ['get']
    queryset = SampleQuestion.objects.all()

    def get_queryset(self, request):
        self.queryset = self.queryset.filter(user_id=self.request.user.id)
        if request.GET.get('position'):
            return self.queryset.filter(position__name=request.GET.get('position'))
        else:
            return self.queryset.none()

    def get(self, request, *args, **kwargs):
        return StreamingHttpResponse(
            serializers.serialize('json', list(self.get_queryset(request)),
                                  fields=('content', 'id', 'limit',)),
            content_type='application/json'
        )


class CompetenciesList(LoginRequiredMixin, View):
    http_method_names = ['get']
    queryset = Competency.objects.all()

    def get_queryset(self, request):
        if request.GET.get('competency'):
            return self.queryset.filter(name__icontains=request.GET.get('competency'))
        else:
            return self.queryset

    def get(self, request, *args, **kwargs):
        return StreamingHttpResponse(
            serializers.serialize('json', list(self.get_queryset(request)), fields=('name', 'id')),
            content_type='application/json'
        )


class QuestionForCompetency(LoginRequiredMixin, View):
    http_method_names = ['get']

    def get_queryset(self, request):
        if request.GET.get('competency'):
            return SampleQuestion.objects.filter(competency__name=request.GET.get('competency'))
        else:
            return SampleQuestion.objects.none()

    def get(self, request, *args, **kwargs):
        return StreamingHttpResponse(
            serializers.serialize('json', list(self.get_queryset(request)),
                                  fields=('content', 'id')),
            content_type='application/json'
        )


class SampleQuestionDeleteView(AjaxRequestMixin, LoginRequiredMixin, DeleteView):
    template_name = 'vw_question/form_delete.html'
    model = SampleQuestion

    def get_success_url(self):
        return reverse_lazy('questions')


class SampleQuestionListView(LoginRequiredMixin, ListView):
    model = SampleQuestion
    template_name = "vw_question/index.html"
    context_object_name = 'questions'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class SampleQuestionUpdateView(AjaxRequestMixin, LoginRequiredMixin, UpdateView):
    model = SampleQuestion
    template_name = "vw_question/edit_form.html"
    form_class = SampleQuestionForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        data = super(SampleQuestionUpdateView, self).get_context_data(**kwargs)
        if self.object.position:
            data.update({'position': self.object.position.name})
        if self.object.competency:
            data.update({'competency': self.object.competency.name})
        return data

    def form_valid(self, form):
        form_data = form.save(commit=False)
        form_data.user = self.request.user
        if self.request.POST.get('position'):
            role, _ = Position.objects.get_or_create(
                name=self.request.POST['position'],
                user=self.request.user
            )
            form_data.position = role
        else:
            form_data.position = None
        if self.request.POST.get('competency'):
            role, _ = Competency.objects.get_or_create(name=self.request.POST['competency'])
            form_data.competency = role
        else:
            form_data.competency = None
        form_data.save()
        return super(SampleQuestionUpdateView, self).form_valid(form)

vw_question/templates/vw_question/create_form.html
{% load i18n %}

<form class="form-horizontal" id="addQuestionForm" method="post" action="{% url 'create_question' %}">
    <div class="modal-header">
        <button type="button" class="close"  data-dismiss="modal" data-action="close-modal" aria-hidden="true">&times;
        </button>
        <h4 class="modal-title">{% trans 'Add Question Template' %}</h4>
    </div>
    <div class="modal-body">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                <label for="{{ field.id_for_label }}" class="control-label col-lg-4">{{ field.label }}</label>
                <div class="col-lg-8">
                    {{ field }}
                    <div class="help-block">
                        {% for error in field.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <label for="id_position" class="control-label col-lg-4">{% trans 'Position' %}</label>
            <div class="col-lg-8">
                <input id="id_position" type="text" name="position" value="{% if position %}{{ position }}{% endif %}" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label for="id_competency" class="control-label col-lg-4">{% trans 'Competency' %}</label>
            <div class="col-lg-8">
                <input id="id_competency" type="text" name="competency" value="{% if competency %}{{ competency }}{% endif %}" class="form-control">
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-success" data-action="create_question" value="{% trans 'Add' %}">
        <button type="button" class="btn btn-default" data-action="close-modal" data-dismiss="modal">{% trans 'Close' %}</button>
    </div>
</form>

vw_question/templates/vw_question/edit_form.html
{% load i18n %}

<form class="form-horizontal" id="editQuestionForm" method="post">
    <div class="modal-header">
        <button type="button" class="close"  data-dismiss="modal" data-action="close-modal" aria-hidden="true">x
        </button>
        <h4 class="modal-title">{% trans 'Add Question Template' %}</h4>
    </div>
    <div class="modal-body">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                <label for="{{ field.id_for_label }}" class="control-label col-lg-4">{{ field.label }}</label>
                <div class="col-lg-8">
                    {{ field }}
                    <div class="help-block">
                        {% for error in field.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <label for="id_position" class="control-label col-lg-4">{% trans 'Position' %}</label>
            <div class="col-lg-8">
                <input id="id_position" type="text" name="position" value="{{ position }}" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label for="id_competency" class="control-label col-lg-4">{% trans 'Competency' %}</label>
            <div class="col-lg-8">
                <input id="id_competency" type="text" name="competency" value="{% if competency %}{{ competency }}{% endif %}" class="form-control">
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-success" data-action="edit_question" value="{% trans 'Update' %}">
        <button type="button" class="btn btn-default" data-action="close-modal" data-dismiss="modal">{% trans 'Close' %}</button>
    </div>
</form>

vw_question/templates/vw_question/form_delete.html
{% load i18n %}
<div class="modal-dialog">
    <div class="modal-content">
        <form class="form-horizontal" id="delForm" method="post" action="{% url 'del_question' object.id %}">
            {% csrf_token %}
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">{% trans 'Delete Question' %}</h4>
            </div>
            <div class="modal-body">
                <p>{% trans 'Are you sure you wish to delete this question?' %}</p>
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-danger" value="{% trans 'Yes' %}">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'No' %}</button>
            </div>
        </form>
    </div>
</div>

vw_question/templates/vw_question/index.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.8.23/themes/base/jquery-ui.css">
{% endblock %}

{% block content %}
    {% csrf_token %}
    <div class="outer">
        <div class="inner bg-light lter">
            <div class="row">
                <div class="col-lg-12">
                    <div class="box">
                        <header>
                            <div class="icons"><i class="fa fa-question-circle"></i></div>
                            <h5>{% trans 'Question Templates' %}</h5>
                            <div class="toolbar">
                                <div class="btn-group">
                                    <button class="btn btn-sm btn-default" data-toggle="modal" href="#addQuestionModal"
                                            data-action="addQuestion">Add <span class="hidden-xs">{% trans 'Question' %}</span>
                                    </button>
                                </div>
                            </div>
                        </header>
                        <div id="collapse4" class="body">
                            <table id="dataTable" class="table table-condensed table-hover table-striped">
                                <thead>
                                <tr>
                                    <th width="10%">{% trans 'Type' %}</th>
                                    <th width="10%">{% trans 'Competency' %}</th>
                                    <th width="10%">{% trans 'Position' %}</th>
                                    <th width="60%">{% trans 'Content' %}</th>
                                    <th width="10%">{% trans 'Actions' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for question in questions %}
                                    <tr>
                                        <td class="type{{ question.id }}">{{ question.type }}</td>
                                        <td class="type{{ question.id }}">{{ question.competency.name|default:"-" }}</td>
                                        <td class="type{{ question.id }}">{{ question.position.name|default:"-" }}</td>
                                        <td class="content{{ question.id }}">{{ question.content }}</td>
                                        <td>
                                            <button class="btn btn-default btn-xs edit-btn" title="edit"
                                                    data-edit="{% url 'edit_question' question.id %}"
                                                    data-toggle="modal" href="#editQuestionModal"
                                                    data-action="editQuestionModal"><i
                                                    class="glyphicon glyphicon-edit"></i></button>
                                            <button type="button" class="btn btn-default btn-xs del-btn"
                                                    title="delete" data-url="{% url 'del_question' question.id %}">
                                                <i class="fa fa-close"></i></button>
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="4"
                                            style="text-align: center;">{% trans 'No Question Template' %}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block modal %}
    <div id="addQuestionModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
    <div id="editQuestionModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
    <div id="delConfirmModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="form-horizontal" id="delForm" method="post" action="">
                    {% csrf_token %}
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">{% trans 'Delete Invite Message' %}</h4>
                    </div>
                    <div class="modal-body">
                        <p>{% trans 'Are you sure you wish to delete this invite message?' %}</p>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-danger" value="{% trans 'Yes' %}">
                        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'No' %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_footer %}
    <style>
        .ui-widget {
            font-size: 0.8em;
            line-height: 0.6em;
        }

        .ui-widget .ui-widget {
            font-size: 0.7em;
        }

        .ui-menu-item {
            font-size: 7pt;
        }

        .sel-candidate {
            font-weight: bold;
        }

        .ui-dialog .ui-dialog-title {
            line-height: 1.6em;
        }

        .ui-dialog {
            z-index: 9990;
        }
    </style>
    <script src="https://code.jquery.com/ui/1.8.23/jquery-ui.js"></script>
    <script>
      var urlPositionsSuggestions = '{% url "positions_list" %}';
      var urlCompetenciesSuggestions = '{% url "competencies_list" %}';
      $(function () {
        // Remove form from Add Question modal
        $('body').on('click', 'input[data-action="create_question"]', function () {
          $.post("{% url 'create_question' %}", $(this).closest('form').serialize(),
            function (data) {
              var block = $('#addQuestionModal');

              if (data.status === 'ok') {
                location.reload();
              } else {
                // removing old form from HTML DOM
                block.find('.modal-content').find('form').remove();
                // adding form with validations to HTML DOM
                $(data.form).appendTo(block.find('.modal-content'));
              }
            }
          );
        });

        // Close modal and remove form
        $('body').on('click', 'button[data-action="close-modal"]', function () {
          $(this).closest('.modal-content').find('form').remove();
          autocompletePatched = false;
          autocompleteCompetencyPatched = false;
        });

        // Append create question form to modal window
        $('button[data-action="addQuestion"]').click(function () {
          $.get("{% url 'create_question' %}",
            function (data) {
              var block = $('#addQuestionModal');
              // added for opening modal window
              block.addClass('in');
              block.attr('attr', 'display:block');
              $(data).appendTo(block.find('.modal-content'));
            }
          );
        });

        // Append edit question form to modal window
        $('button[data-action="editQuestionModal"]').click(function () {
          var url = $(this).data('edit');
          $.get(url,
            function (data) {
              var block = $('#editQuestionModal');
              // added for opening modal window
              block.addClass('in');
              block.attr('attr', 'display:block');
              $(data).appendTo(block.find('.modal-content'));
              $('#editQuestionForm').attr('action', url);
            }
          );
        });

        $('body').on('click', 'input[data-action="edit_question"]', function () {
          var form = $(this).closest('form');
          $.post(form.attr('action'), form.serialize(),
            function (data) {
              var block = $('#editQuestionModal');

              if (data.status === 'ok') {
                location.reload();
              } else {
                // removing old form from HTML DOM
                block.find('.modal-content').find('form').remove();
                // adding form with validations to HTML DOM
                $(data.form).appendTo(block.find('.modal-content'));
              }
            }
          );
        });

        // Remove SampleQuestion from DB
        $('.del-btn').click(function () {
          $.get($(this).data('url'), function (e) {
            $('#delConfirmModal').empty();
            $('#delConfirmModal').append(e);
            $('#delConfirmModal').modal('toggle');
          })
        });

        var autocompletePatched = false;
        var autocompleteCompetencyPatched = false;

        function monkeyPatchAutocomplete() {
          var oldFn = $.ui.autocomplete.prototype._renderItem;

          $.ui.autocomplete.prototype._renderItem = function (ul, item) {
            var re = new RegExp("\\b" + this.term, "i");
            var t = item.label.replace(re, "<span style='font-weight:bold;color:Blue;'>" + this.term + "</span>");
            return $("<li></li>")
              .data("item.autocomplete", item)
              .append("<a>" + t + "</a>")
              .appendTo(ul);
          };
        }

        function getValue(object, path, defaultValue) {
          const pathParts = path instanceof Array ? path : path.split('.');

          if (!pathParts.length || typeof object !== 'object') return defaultValue;

          const currentPathPart = pathParts[0];
          const restPath = pathParts.slice(1);

          if (pathParts.length === 1) return object[currentPathPart];

          return getValue(object[currentPathPart], restPath, defaultValue);
        }

        function getPositionsSuggestions({value, cb}) {
          $.ajax({
            url: urlPositionsSuggestions + '?position=' + value,
            cache: false,
            success: function (result) {
              cb(
                result
                  .map(function (pos) {
                    return getValue(pos, 'fields.name', '')
                  })
                  .filter(function (pos) {
                    return pos
                  })
              );
            },
          })
        }

        function getCompetenciesSuggestions({value, cb}) {
          $.ajax({
            url: urlCompetenciesSuggestions + '?competency=' + value,
            cache: false,
            success: function (result) {
              cb(
                result
                  .map(function (pos) {
                    return getValue(pos, 'fields.name', '')
                  })
                  .filter(function (pos) {
                    return pos
                  })
              );
            },
          })
        }

        $('body').on('focus', '#id_position', function () {
          if (autocompletePatched) return;

          autocompletePatched = true;
          monkeyPatchAutocomplete();

          $("#id_position").autocomplete({
            source: function (req, responseFn) {
              const value = req.term;

              if (!value) {
                return responseFn([]);
              }
              getPositionsSuggestions({value, cb: responseFn});
            },
          });
        });

        $('body').on('focus', '#id_competency', function () {
          if (autocompleteCompetencyPatched) return;

          autocompleteCompetencyPatched = true;
          monkeyPatchAutocomplete();

          $("#id_competency").autocomplete({
            source: function (req, responseFn) {
              const value = req.term;

              if (!value) {
                return responseFn([]);
              }
              getCompetenciesSuggestions({value, cb: responseFn});
            },
          });
        });

      });
    </script>
{% endblock %}